using System.Globalization;
using System.Text;

namespace JustDownload.Core.Media.YtDlp;

/// <summary>
/// Serializes captured cookies into yt-dlp's expected Netscape HTTP Cookie File format — the same format
/// a browser's own cookie export produces, and the format <c>AppSettings.YtDlpCookieFilePath</c> already
/// expects via <c>--cookies &lt;path&gt;</c> (<see cref="YtDlpMediaExtractor"/>). Pure and deterministic:
/// no I/O, no dependency on how the cookies were captured.
/// </summary>
public static class NetscapeCookieFileWriter
{
    private const string Header =
        "# Netscape HTTP Cookie File\n# Generated by JustDownload — do not edit.\n\n";

    /// <summary>
    /// Writes every record as one tab-separated line: domain, include-subdomains flag, path, secure flag,
    /// expiry, name, value — the seven fields curl/yt-dlp's Netscape cookie-jar parser expects, in order.
    /// </summary>
    public static string Write(IReadOnlyList<NetscapeCookieRecord> cookies)
    {
        ArgumentNullException.ThrowIfNull(cookies);

        var builder = new StringBuilder(Header);
        foreach (NetscapeCookieRecord cookie in cookies)
        {
            builder
                .Append(cookie.Domain).Append('\t')
                .Append(cookie.IncludeSubdomains ? "TRUE" : "FALSE").Append('\t')
                .Append(cookie.Path).Append('\t')
                .Append(cookie.Secure ? "TRUE" : "FALSE").Append('\t')
                .Append(cookie.ExpiresUnixSeconds.ToString(CultureInfo.InvariantCulture)).Append('\t')
                .Append(cookie.Name).Append('\t')
                .Append(cookie.Value).Append('\n');
        }

        return builder.ToString();
    }
}
